services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "5555:5556"
    volumes:
      - .:/app
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    # command: npm run dev
  db:
    image: postgres:12-alpine
    container_name: wbs-app-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: